export const GET_EMPLOYEE = 'GET_EMPLOYEE';
export const GET_EMPLOYEE_SUCCESS = 'GET_EMPLOYEE_SUCCESS';
export const GET_EMPLOYEE_FAILURE = 'GET_EMPLOYEE_FAILURE';
export const ADD_EMPLOYEE = 'ADD_EMPLOYEE'
export const EDIT_EMPLOYEE = 'EDIT_EMPLOYEE'
export const GET_EMPLOYEE_BY_ID = 'GET_EMPLOYEE_BY_ID'
export const DELETE_EMPLOYEE = 'DELETE_EMPLOYEE'